[package]
name = "rs-avl"
version = "0.1.0"
edition = "2024"
description = "A generic AVL tree with range queries and traversal iterators"
documentation = "https://docs.rs/rs-avl"
homepage = "https://github.com/anuradhawick/rs-avl"
repository = "https://github.com/anuradhawick/rs-avl"
readme = "rust_readme.md"
keywords = ["avl", "tree", "collection", "data-structure"]
categories = ["data-structures"]
include = [
    "Cargo.toml",
    "Cargo.lock",
    "rust_readme.md",
    "rs_avl.pyi",
    "src/**",
    "tests/avl_tree.rs",
    "examples/rust_avl.rs",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rs_avl"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.29.0", features = ["extension-module", "abi3-py310", "experimental-inspect"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
